[plugins]
shadow = { id = "io.github.goooler.shadow", version = "8.1.8"}
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.3.0" }

[versions]
# Tooling
indra = "3.1.3"
jspecify = "1.0.0"

# Bukkit
paper = "1.21-R0.1-SNAPSHOT"

# Examples
cloud = "2.0.0-SNAPSHOT"

[libraries]
# Tooling
indra = { group = "net.kyori", name = "indra-common", version.ref = "indra" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }

# Bukkit
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

# Examples
cloud-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud" }
